-- 为users表添加新字段
ALTER TABLE users ADD COLUMN gender VARCHAR(10) DEFAULT NULL;
ALTER TABLE users ADD COLUMN age VARCHAR(10) DEFAULT NULL;
ALTER TABLE users ADD COLUMN grade VARCHAR(20) DEFAULT NULL;
ALTER TABLE users ADD COLUMN address VARCHAR(255) DEFAULT NULL; 